const UPSTREAM_TIMEOUT = 500;
const DATA_WORKER_PORT = 8000;
const MAX_CONCURRENT_REQUESTS = 50;
const RETRY_COUNT = 2;
const LOG_LEVEL = "info";

module.exports = {
  UPSTREAM_TIMEOUT,
  DATA_WORKER_PORT,
  MAX_CONCURRENT_REQUESTS,
  RETRY_COUNT,
  LOG_LEVEL,
};
