apiVersion: v1
kind: Service
metadata:
  name: core-business
  namespace: aiops
  labels:
    app: core-business
spec:
  selector:
    app: core-business
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
