apiVersion: v1
kind: Service
metadata:
  name: data-worker
  namespace: aiops
  labels:
    app: data-worker
spec:
  selector:
    app: data-worker
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
